site_name: calendar_api
site_description: A clone of Google Calendar API
repo_url: https://github.com/jsgilberto/calendar-rest-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/jsgilberto">jsgilberto</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
